[theme]
primaryColor = "#a7dadc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f9f9"
textColor = "#1e293b"
font = "sans serif"

[server]
port = 8501
headless = false
runOnSave = true
maxUploadSize = 200

[client]
toolbarMode = "minimal"
showErrorDetails = false

[logger]
level = "info"

[runner]
magicEnabled = true

